### ISSUE TITLE
Intermittently window decorations do not respond

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#14] opened 2019-06-09 23:21 UTC
Twice now with the current alpha, the close, maximise etc. buttons on the windows of various apps - Nemo, Sublime, Firefox - have stopped responding. I think the problem may have to do with layers. For, I have the program Rainlendar that draws to the desktop and, on one occasion that I had the probem, the problem disappeared when I quit Rainlendar (and on the other occasion the problem seemed to solve itself). (Still, I have a Conky too . .)

**Comment by JosephMcc** [comment] 2019-06-09 23:26
You are running the 4.0.10-unstable-201906071516~ubuntu18.04.1 version?

**Comment by LinuxOnTheDesktop** [comment] 2019-06-09 23:31
Well, my package `cinnamon-common` shows that particular label, but I can't find any other packages that have that same label. `apt` is not offering me anything (and I have the daily builds 'pinned' at priority 700 in a 'ppa pref' file).

**Comment by JosephMcc** [comment] 2019-06-09 23:33
The issue you are having should be fixed on the latest master but it hasn't been pushed to the ppa yet. The problem is actually the area where notifications are shown. Once one shows that area is blocked from any input. That's why only parts of the titlebar are not working. They are beneath that area.

I'm going to go ahead and close this for now. The next update you get for cinnamon should fix the issue.

**Closed by JosephMcc** 2019-06-09 23:33 UTC
